version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - docker
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
      - javascript
    versioning-strategy: "increase"
